/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b2482b14-33b8-431e-b4ba-ef5dd6183565",
    "aws_cognito_region": "us-west-2",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "OrderFlowers_dev",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
